sudo: required
dist: trusty
language: cpp

env:
  global:
    - /usr/local/bin:$PATH

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - COMPILER="" BUILD_TYPE="-c dbg"
        - CXX=g++-5
        - CC=gcc-5
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env:
        - COMPILER="" BUILD_TYPE="-c dbg"
        - CXX=clang++
        - CC=clang

install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo add-apt-repository ppa:dreal/dreal -y;
      sudo apt update;
      sudo apt install autoconf automake bison coinor-libclp-dev flex libtool pkg-config libibex-dev libnlopt-dev;
      export BAZEL_VERSION=0.10.1;
      wget https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel_${BAZEL_VERSION}-linux-x86_64.deb;
      sudo dpkg -i bazel_${BAZEL_VERSION}-linux-x86_64.deb;
    fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      brew update;
      brew install autoconf bazel libtool pkg-config dreal-deps/ibex/ibex@2.6.5 nlopt || true;
    fi

script:
  - CXX=${CXX} CC=${CC} bazel run //:check_sat ${COMPILER} ${BUILD_TYPE}
