sudo: required
dist: trusty
language: cpp

env:
  global:
    - /usr/local/bin:$PATH

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - COMPILER="" BUILD_TYPE="-c dbg"

install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo add-apt-repository ppa:dreal/dreal -y;
      sudo apt update;
      sudo apt install autoconf automake bison coinor-libclp-dev flex libtool pkg-config libibex-dev libnlopt-dev;
      wget https://github.com/bazelbuild/bazel/releases/download/0.5.4/bazel_0.5.4-linux-x86_64.deb;
      sudo dpkg -i bazel_0.5.4-linux-x86_64.deb;
    fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      brew update;
      brew install autoconf bazel libtool pkg-config dreal-deps/ibex/ibex nlopt || true;
    fi

script:
  - bazel run //:check_sat ${COMPILER} ${BUILD_TYPE}
