sudo: required
dist: trusty
language: cpp

env:
  global:
    - /usr/local/bin:$PATH

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env:
        - BUILD_TYPE="dbg"
        - CXX_COMPILER=g++-5
        - CC_COMPILER=gcc-5
    - os: osx
      osx_image: xcode9.2  # macOS-10.12
      compiler: clang
      env:
        - BUILD_TYPE="dbg"
        - CXX_COMPILER=clang++
        - CC_COMPILER=clang
    - os: osx
      osx_image: xcode9.4  # macOS-10.13
      compiler: clang
      env:
        - BUILD_TYPE="dbg"
        - CXX_COMPILER=clang++
        - CC_COMPILER=clang

install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      curl -s https://raw.githubusercontent.com/dreal/dreal4/master/setup/ubuntu/14.04/install_prereqs.sh | sudo bash;
    fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      curl -s https://raw.githubusercontent.com/dreal/dreal4/master/setup/mac/install_prereqs.sh | bash || true;
    fi

script:
  - CXX=${CXX_COMPILER} CC=${CC_COMPILER} bazel run //:check_sat -c ${BUILD_TYPE}
